using System;
using System.ComponentModel;
using System.Xml.Serialization;

using UnityEngine;

namespace TurboTurbo.Modeling;

/// <summary>Models turbocharging. Charge depends on boost pressure, which is generated by exhaust power.</summary>
public sealed class TurboCharger : ICharger
{
    /// <summary>Configuration constants. Defaults give a reasonable starting point.</summary>
    [XmlType("TurboChargerSettings")]
    public sealed class Settings
    {
        internal const float DefaultLambdaCalibration = 1.41f;
        internal const float DefaultBoostChargeMultiplier = 1.125f;
        internal const float DefaultRpmBoostExponent = 1.2f;
        internal const float DefaultTauUp = 3.0f;
        internal const float DefaultTauDown = 1.0f;
        internal const float DefaultMinSpoolTau = 0.5f;
        internal const float DefaultThermalK = 0.8f;
        internal const float DefaultSurgeRateThreshold = 15f;

        [DefaultValue(DefaultLambdaCalibration)]
        public float LambdaCalibration { get; set; } = DefaultLambdaCalibration;

        [DefaultValue(DefaultBoostChargeMultiplier)]
        public float BoostChargeMultiplier { get; set; } = DefaultBoostChargeMultiplier;

        [DefaultValue(DefaultRpmBoostExponent)]
        public float RpmBoostExponent { get; set; } = DefaultRpmBoostExponent;

        [DefaultValue(DefaultTauUp)]
        public float TauUp { get; set; } = DefaultTauUp;

        [DefaultValue(DefaultTauDown)]
        public float TauDown { get; set; } = DefaultTauDown;

        [DefaultValue(DefaultMinSpoolTau)]
        public float MinSpoolTau { get; set; } = DefaultMinSpoolTau;

        [DefaultValue(DefaultThermalK)]
        public float ThermalK { get; set; } = DefaultThermalK;

        /// <summary>Governor drop rate [1/s] that triggers a surge while boost is high.</summary>
        [DefaultValue(DefaultSurgeRateThreshold)]
        public float SurgeRateThreshold { get; set; } = DefaultSurgeRateThreshold;

        public Settings()
        {
        }

        public Settings(Settings other)
        {
            LambdaCalibration = other.LambdaCalibration;
            BoostChargeMultiplier = other.BoostChargeMultiplier;
            RpmBoostExponent = other.RpmBoostExponent;
            TauUp = other.TauUp;
            TauDown = other.TauDown;
            MinSpoolTau = other.MinSpoolTau;
            ThermalK = other.ThermalK;
            SurgeRateThreshold = other.SurgeRateThreshold;
        }
    }

    private readonly Settings _tuning;
    private float _prevGovernor;

    public Settings Tuning => _tuning;

    /// <summary>Current turbo boost pressure ratio [0..1].</summary>
    public float Boost { get; private set; }

    public bool Surging { get; private set; }

    public float LambdaCalibration => _tuning.LambdaCalibration;

    /// <summary>Exhaust-gas energy proxy [0..1], the boost target.</summary>
    public float ExhaustHeat { get; private set; }

    /// <summary>
    /// Per-stroke cylinder charge. 1.0 = naturally aspirated; boost raises it further, up to 1 + BoostChargeMultiplier
    /// </summary>
    public float Charge => 1f + _tuning.BoostChargeMultiplier * Boost;

    public TurboCharger(Settings settings)
    {
        _tuning = settings ?? throw new ArgumentNullException(nameof(settings));
    }

    public void Tick(float delta, float fuelPerStroke, float overfuel, float rpmNorm, float governorNorm, bool engineOn)
    {
        var s = _tuning;

        var target = fuelPerStroke * Mathf.Pow(rpmNorm, s.RpmBoostExponent);
        ExhaustHeat = target;

        var tau = fuelPerStroke > Boost
            ? Mathf.Max(s.MinSpoolTau, s.TauUp / (1f + s.ThermalK * overfuel))
            : s.TauDown;
        Boost += (target - Boost) * (1f - Mathf.Exp(-delta / tau));

        var governorRate = (_prevGovernor - governorNorm) / Mathf.Max(0.001f, delta);
        Surging = engineOn && governorRate > s.SurgeRateThreshold && Boost > 0.75f;
        _prevGovernor = governorNorm;
    }

    public ICharger Clone() => new TurboCharger(new Settings(_tuning));
}