using System;

using UnityEngine;

namespace TurboTurbo.Modeling;

/// <summary>Models turbocharging. Charge depends on boost pressure, which is generated by exhaust power.</summary>
public sealed class TurboCharger : ICharger
{
    /// <summary>Configuration constants. Defaults give a reasonable starting point.</summary>
    public sealed class Settings
    {
        public float LambdaCalibration { get; set; } = 1.74f;
        public float BoostChargeMultiplier { get; set; } = 1.125f;
        public float RpmBoostExponent { get; set; } = 1.2f;
        public float TauUp { get; set; } = 3.0f;
        public float TauDown { get; set; } = 1.0f;
        public float MinSpoolTau { get; set; } = 0.5f;
        public float ThermalK { get; set; } = 0.8f;

        /// <summary>Demand drop rate [1/s] that triggers a surge while boost is high.</summary>
        public float SurgeRateThreshold { get; set; } = 15f;

        public Settings()
        {
        }

        public Settings(Settings other)
        {
            LambdaCalibration = other.LambdaCalibration;
            BoostChargeMultiplier = other.BoostChargeMultiplier;
            RpmBoostExponent = other.RpmBoostExponent;
            TauUp = other.TauUp;
            TauDown = other.TauDown;
            MinSpoolTau = other.MinSpoolTau;
            ThermalK = other.ThermalK;
            SurgeRateThreshold = other.SurgeRateThreshold;
        }
    }

    private readonly Settings _tuning;
    private float _prevDemand;

    public Settings Tuning => _tuning;

    /// <summary>Current turbo boost pressure ratio [0..1].</summary>
    public float Boost { get; private set; }

    public bool Surging { get; private set; }

    public float LambdaCalibration => _tuning.LambdaCalibration;

    /// <summary>Exhaust-gas energy proxy [0..1], the boost target.</summary>
    public float ExhaustHeat { get; private set; }

    /// <summary>
    /// Per-stroke cylinder charge. 1.0 = naturally aspirated; boost raises it further, up to 1 + BoostChargeMultiplier
    /// </summary>
    public float Charge => 1f + _tuning.BoostChargeMultiplier * Boost;

    public TurboCharger(Settings settings)
    {
        _tuning = settings ?? throw new ArgumentNullException(nameof(settings));
    }

    public void Tick(float delta, float fuelDemand, float overfuel, float rpmNorm, float throttle, bool engineOn)
    {
        var s = _tuning;

        var target = fuelDemand * Mathf.Pow(rpmNorm, s.RpmBoostExponent);
        ExhaustHeat = target;

        var tau = fuelDemand > Boost
            ? Mathf.Max(s.MinSpoolTau, s.TauUp / (1f + s.ThermalK * overfuel))
            : s.TauDown;
        Boost += (target - Boost) * (1f - Mathf.Exp(-delta / tau));

        var demandRate = (_prevDemand - throttle) / Mathf.Max(0.001f, delta);
        Surging = engineOn && demandRate > s.SurgeRateThreshold && Boost > 0.75f;
        _prevDemand = throttle;
    }

    public ICharger Clone() => new TurboCharger(new Settings(_tuning));
}